# -*- coding: utf-8 -*-
"""email spam classifier

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Eg6bH9aeYHQ3MFo3wPRAq5hq8X1cH4Ly
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
import pickle

data = pd.read_csv('email_spam.csv')

data.tail(2)

data.info()

le = LabelEncoder()
data["title"] = le.fit_transform(data["title"])
data["text"] = le.fit_transform(data["text"])
data["type"] = le.fit_transform(data["type"])

selected_features =['title','text']

data.dropna(inplace=False)

data.dropna(inplace=True)

x = data[selected_features]
y = data['type']
x_train, x_test, y_train, y_test =train_test_split(x,y,test_size=0.2,random_state=42)

model = LogisticRegression()
model.fit(x_train, y_train)

np.random.seed(0)
type= np.random.randint(1,10,100)
text= np.where(type>5,1,0)

with open('LogisticRegression_model.pkl','wb') as f:
    pickle.dump(model,f)